mutation RegisterWithCredentials($registerWithCredentialsInput: registerWithCredentialsInput!) {
  registerWithCredentials(registerWithCredentialsInput: $registerWithCredentialsInput) {
    uid
    name
    image
  }
}


query Companies($distinct: [CompanyScalarFieldEnum!], $where: CompanyWhereInput, $orderBy: [CompanyOrderByWithRelationInput!], $cursor: CompanyWhereUniqueInput, $take: Int, $skip: Int) {
  companies(distinct: $distinct, where: $where, orderBy: $orderBy, cursor: $cursor, take: $take, skip: $skip) {
    updatedAt
    managers {
      createdAt
      displayName
    }
    id
    displayName
    description
    createdAt
    garages {
      updatedAt
      displayName
      description
    }
  }
}



mutation Login($loginInput: LoginInput!) {
  login(loginInput: $loginInput) {
    token
    user{
      uid
      name
      image
    }
  }
}

mutation RegisterWithProvider($registerWithProviderInput: RegisterWithProviderInput!) {
  registerWithProvider(registerWithProviderInput: $registerWithProviderInput) {
    updatedAt
    uid
    name
    image
    createdAt
    admin {
      uid
      updatedAt
    }
    valet {
      uid
      licenceID
      image
      displayName
      createdAt
    }
    manager {
      displayName
      uid
    }
    customer {
      uid
      displayName
    }
  }
}

query GetAuthProvider($uid: String!) {
  getAuthProvider(uid: $uid) {
    type
    uid
  }
}

query SearchGarages(
  $dateFilter: DateFilterInput!
  $locationFilter: LocationFilterInput!
  $slotsFilter: SlotWhereInput
  $garageFilter: GarageFilter
) {
  searchGarages(
    dateFilter: $dateFilter
    locationFilter: $locationFilter
    slotsFilter: $slotsFilter
    garageFilter: $garageFilter
  ) {
    id
    address {
      lat
      lng
      address
    }
    images
    displayName
    availableSlots(dateFilter: $dateFilter, slotsFilter: $slotsFilter) {
      type
      pricePerHour
      count
    }
    verification {
      verified
    }
  }
}