import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@findmyspot/ui/app/globals.css";
import { ApolloProvider } from "@findmyspot/network";
import { SessionProvider } from "@findmyspot/ui/app/components/molecules/SessionProvider";
import { Header } from "@findmyspot/ui/app/components/organisms/Header";
import { Container } from "@findmyspot/ui/app/components/atoms/Container";
import { ToastContainer } from "@findmyspot/ui/app/components/molecules/Toast";
import { MenuItem } from "@findmyspot/util/types";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MENUITEMS: MenuItem[] = [
  { label: 'Search', 'href': '/search' },
  { label: 'Bookings', 'href': '/bookings' }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-25`}
          >

            <Header menuItems={MENUITEMS} />
            <Container>{children}</Container>
            <ToastContainer />
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
